// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABEaBTPF4zb1j_vMQbli5S-RympuQ95Lo',
    appId: '1:696742513156:web:8013a20f11a975d90a0351',
    messagingSenderId: '696742513156',
    projectId: 'certificatezip-f5385',
    authDomain: 'certificatezip-f5385.firebaseapp.com',
    storageBucket: 'certificatezip-f5385.firebasestorage.app',
    measurementId: 'G-VQBVV8347E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0bij9HofkhX_p-5obthSuH5WDT9JYKLQ',
    appId: '1:696742513156:android:2d2e3847252561a90a0351',
    messagingSenderId: '696742513156',
    projectId: 'certificatezip-f5385',
    storageBucket: 'certificatezip-f5385.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMr2dHyCiZ0tb0_t8eg_9mBfv6S-Nop5E',
    appId: '1:696742513156:ios:1e7b44bbf7c8ea460a0351',
    messagingSenderId: '696742513156',
    projectId: 'certificatezip-f5385',
    storageBucket: 'certificatezip-f5385.firebasestorage.app',
    iosBundleId: 'com.example.certificatezip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABEaBTPF4zb1j_vMQbli5S-RympuQ95Lo',
    appId: '1:696742513156:web:6a9c9bd4b74bebc30a0351',
    messagingSenderId: '696742513156',
    projectId: 'certificatezip-f5385',
    authDomain: 'certificatezip-f5385.firebaseapp.com',
    storageBucket: 'certificatezip-f5385.firebasestorage.app',
    measurementId: 'G-PGE4S02L2R',
  );
}
